environment_config:
  path: env_config.dart
  fields:
   API_BASE_URL:
      env_var: API_BASE_URL
      default: "http://localhost:3000/api/"
      dotenv: true
  
   DEVELOPMENT:
      env_var: DEVELOPMENT
      default: true
      dotenv: true
  
  imports:
    - dart:io
